import json
from pathlib import Path

def append_test():
    f = Path("simulator/tests/test_diagnostic.py")
    test_code = """
from recoveriq_sequential_policy.evaluation import evaluate_policy_seed_group
from recoveriq_sequential_policy.models import FrozenSequentialBaselines
from recoveriq_policy_evaluation.diagnostic import run_paired_diagnostic
from recoveriq_simulator.seeds import DIAGNOSTIC_SEEDS

def test_full_trajectory_non_interference():
    baselines_path = (
        Path(__file__).parent.parent.parent
        / "artifacts"
        / "policy"
        / "recoveriq-sequential-v2"
        / "development-baselines-v2.json"
    )
    with open(baselines_path, encoding="utf-8") as f:
        baselines = FrozenSequentialBaselines.model_validate(json.load(f))
    model_root = (
        Path(__file__).parent.parent.parent / "artifacts" / "ml" / "models" / "recovery-model-v2"
    )
    calibration_root = (
        Path(__file__).parent.parent.parent
        / "artifacts"
        / "ml"
        / "calibration"
        / "recovery-model-v2"
    )

    eval_result, eval_frame, _ = evaluate_policy_seed_group(
        seeds=DIAGNOSTIC_SEEDS[:2],
        baselines=baselines,
        normalized_margin_threshold=0.0,
        model_root=model_root,
        calibration_root=calibration_root,
        strategies=("recoveriq_erv_sequential_v2",),
    )

    diag_result = run_paired_diagnostic(
        seeds=DIAGNOSTIC_SEEDS[:2],
        baselines=baselines,
        normalized_margin_threshold=0.0,
        model_root=model_root,
        calibration_root=calibration_root,
    )

    # eval_frame has columns: seed, decision_key, episode_id, ... 
    # Let's compare episode-level metrics directly
    
    assert eval_result["strategy_metrics"]["recoveriq_erv_sequential_v2"]["failed_payments_evaluated"] == diag_result["metrics"]["total_decisions_by_strategy"]["recoveriq_erv_sequential_v2"]

    # We need to ensure that the factual trajectories generated inside run_paired_diagnostic perfectly match those generated by evaluate_policy_seed_group.
    # We will test equality of factual trajectories.
"""
    with open(f, "a", encoding="utf-8") as file:
        file.write(test_code)

append_test()
