from collections.abc import Mapping
from typing import Any

from app.ai.schemas import DecisionExplanation


class FakeLLMProvider:
    """Deterministic provider used by unit and integration tests."""

    async def health_check(self) -> bool:
        return True

    async def explain_decision(self, evidence: Mapping[str, Any]) -> DecisionExplanation:
        selected_action = str(evidence.get("selected_action", "NO_ACTION_SELECTED"))
        return DecisionExplanation(
            headline="Recovery decision evidence is available",
            summary=f"The deterministic test provider received action {selected_action}.",
            key_factors=["Structured evidence passed schema validation"],
            uncertainty="This response is generated by the test provider.",
        )
