from collections.abc import Mapping
from typing import Any

from app.ai.schemas import DecisionExplanation


class FakeLLMProvider:
    """Deterministic provider used by unit and integration tests."""

    async def health_check(self) -> bool:
        return True

    async def explain_decision_trace(
        self, evidence: Mapping[str, Any]
    ) -> DecisionExplanation:
        selected_action = str(evidence.get("selected_action", "NO_ACTION_SELECTED"))
        return DecisionExplanation(
            summary=f"The deterministic test provider received action {selected_action}.",
            factors=["Structured evidence passed schema validation"],
            confidence=1.0,
            limitations=["This response is generated by the test provider."],
        )

    async def explain_recovery_case(
        self, evidence: Mapping[str, Any]
    ) -> DecisionExplanation:
        return await self.explain_decision_trace(evidence)

    async def explain_decision(self, evidence: Mapping[str, Any]) -> DecisionExplanation:
        """Compatibility alias for the original Phase 1 method."""
        return await self.explain_decision_trace(evidence)
