"""Add ProviderTruthTriangulation confirmation fields

Revision ID: 92502675fbb2
Revises: 4d7a0f3b21c8
Create Date: 2026-09-02 22:24:25.493483

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92502675fbb2"
down_revision: str | Sequence[str] | None = "4d7a0f3b21c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_webhook_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "provider_confirmation_status",
                sa.Enum(
                    "NOT_REQUIRED",
                    "PENDING",
                    "CONFIRMED",
                    "MISMATCH",
                    name="provider_confirmation_status",
                    native_enum=False,
                ),
                nullable=False,
                server_default="NOT_REQUIRED",
            )
        )
        batch_op.add_column(
            sa.Column("provider_confirmation_method", sa.String(length=80), nullable=True)
        )
        batch_op.add_column(
            sa.Column("provider_confirmed_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_webhook_events", schema=None) as batch_op:
        batch_op.drop_column("provider_confirmed_at")
        batch_op.drop_column("provider_confirmation_method")
        batch_op.drop_column("provider_confirmation_status")

    # ### end Alembic commands ###
