from enum import StrEnum


class PaymentMethod(StrEnum):
    CARD = "CARD"
    UPI = "UPI"
    NETBANKING = "NETBANKING"
    MANDATE = "MANDATE"


class FailureReason(StrEnum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    ISSUER_UNAVAILABLE = "ISSUER_UNAVAILABLE"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    INSTRUMENT_EXPIRED = "INSTRUMENT_EXPIRED"
    MANDATE_INACTIVE = "MANDATE_INACTIVE"
    TEMPORARY_NETWORK_ERROR = "TEMPORARY_NETWORK_ERROR"
    CUSTOMER_ACTION_REQUIRED = "CUSTOMER_ACTION_REQUIRED"
    UNKNOWN_TRANSIENT_ERROR = "UNKNOWN_TRANSIENT_ERROR"


class FailureSource(StrEnum):
    CUSTOMER = "CUSTOMER"
    ISSUER = "ISSUER"
    NETWORK = "NETWORK"
    INSTRUMENT = "INSTRUMENT"
    MANDATE = "MANDATE"
    UNKNOWN = "UNKNOWN"


class TrueFailureCause(StrEnum):
    LIQUIDITY_SHORTFALL = "LIQUIDITY_SHORTFALL"
    ISSUER_DEGRADATION = "ISSUER_DEGRADATION"
    AUTHENTICATION_FRICTION = "AUTHENTICATION_FRICTION"
    INVALID_INSTRUMENT = "INVALID_INSTRUMENT"
    INACTIVE_MANDATE = "INACTIVE_MANDATE"
    NETWORK_INSTABILITY = "NETWORK_INSTABILITY"
    CUSTOMER_CONFIRMATION = "CUSTOMER_CONFIRMATION"
    UNKNOWN_TEMPORARY = "UNKNOWN_TEMPORARY"


class InstrumentState(StrEnum):
    VALID = "VALID"
    UNSTABLE = "UNSTABLE"
    EXPIRED = "EXPIRED"
    INACTIVE = "INACTIVE"


class ActionType(StrEnum):
    WAIT = "WAIT"
    RETRY_NOW = "RETRY_NOW"
    RETRY_LATER = "RETRY_LATER"
    SEND_NUDGE = "SEND_NUDGE"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    REQUEST_PAYMENT_METHOD_UPDATE = "REQUEST_PAYMENT_METHOD_UPDATE"
    OFFER_ALTERNATE_METHOD = "OFFER_ALTERNATE_METHOD"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    STOP = "STOP"


class EventType(StrEnum):
    PAYMENT_DUE = "PAYMENT_DUE"
    PAYMENT_ATTEMPTED = "PAYMENT_ATTEMPTED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED"
    STATUS_EVENT_DELIVERED = "STATUS_EVENT_DELIVERED"
    RECOVERY_ACTION_SCHEDULED = "RECOVERY_ACTION_SCHEDULED"
    RECOVERY_ACTION_EXECUTED = "RECOVERY_ACTION_EXECUTED"
    CUSTOMER_CONTACTED = "CUSTOMER_CONTACTED"
    INCIDENT_STARTED = "INCIDENT_STARTED"
    INCIDENT_ENDED = "INCIDENT_ENDED"
    RECOVERY_SUCCEEDED = "RECOVERY_SUCCEEDED"
    RECOVERY_STOPPED = "RECOVERY_STOPPED"
